# This is a workflow to pack py file to exe

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello World!

    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14
    
    - name: Install requirements and installer
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run pyinstaller
      run: |
        python -m PyInstaller -F -w ws_tcg_2.py

